In [10]:
#Iris flower has three species; setosa, versicolor, and virginica, which differs accordir_ to
#their measurements. Now assume that you have the measurements of the iris flowers according to
#their species, and here your task is to train a machine learning model that can learn from
#the measurements of the iris species and classify them. Although the Scikit-learn library
#provides a dataset for iris flower classification, you can also download the same dataset from
#here for the task of iris flower classification with Machine Learning.


In [20]:
import pandas as pd
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [21]:
# Load the Iris dataset
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [22]:
# Convert to DataFrame for better visualization
iris_df = pd.DataFrame(data=np.c_[iris['data'], iris['target']], 
                       columns=iris['feature_names'] + ['target'])

In [24]:
# Display the first few rows of the dataset
print(iris_df.head())

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0  


In [25]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [26]:
# Standardize the data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [27]:
# Making predictions
y_pred = clf.predict(X_test)

In [28]:
# Train a Logistic Regression classifier
log_reg = LogisticRegression(multi_class='ovr', solver='liblinear')
log_reg.fit(X_train, y_train)

LogisticRegression(multi_class='ovr', solver='liblinear')

In [29]:
# Make predictions
y_pred = log_reg.predict(X_test)

In [30]:
# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')

print('Classification Report:')
print(classification_report(y_test, y_pred, target_names=iris.target_names))

print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.91
Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        19
  versicolor       1.00      0.69      0.82        13
   virginica       0.76      1.00      0.87        13

    accuracy                           0.91        45
   macro avg       0.92      0.90      0.89        45
weighted avg       0.93      0.91      0.91        45

Confusion Matrix:
[[19  0  0]
 [ 0  9  4]
 [ 0  0 13]]
